id: P009189
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:27:14.310347
source_metadata:
  id: bdr:W8LS19099
  title: བདེ་འཇགས་དོ་དམ་ཆད་གཅོད་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    a6cd0baa6b834e8ea7ffaeb6e48fda22:
      image_group_id: I8LS19101
      title: ''
      volume_number: 1
      total_pages: 222
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
