id: I00F9AD1E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:13:28+00:00'
last_modified: '2022-06-08T09:15:14.504043+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19099
  title: བདེ་འཇགས་དོ་དམ་ཆད་གཅོད་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4FDB:
      image_group_id: I8LS19101
      title: ''
      total_pages: 222
      order: 1
      base_file: 4FDB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
